from classes import *
school = School()
grade = Grade()
subject_proge = Subject()
teacher = Teacher()
school.adding_name()
grade.naming_grade()
teacher.naming_teachers()
school.adding_grades(grade)
school.adding_teacher(teacher)
subject_proge.naming_subject()
subject_proge.add_grade_to_subject(grade)
school.adding_subject(subject_proge)
subject_proge.adding_teacher(teacher)
teacher.teaching_subjects(subject_proge)
teacher.teaching_school(school)
print(school.name)
print(grade.name)
print(school.grade)
print(school.subject)
print(school.teacher)
print(subject_proge.name)
print(subject_proge.teacher)
print(subject_proge.required_to_study)
print(teacher.name)
print(teacher.schools)
print(teacher.subjects)